{
  gStyle->SetOptStat(0);

  TFile *f = new TFile("~/LowE/AnalysisPlots/oldest/DetectorToECalib_1.root");
  //TFile *f = new TFile("~/LowE/AnalysisPlots/oldest/TuneWFCutsDS0.root");
  TH2F *h0 = (TH2F*)f->Get("htrapENFCalHG664");
  //TH2F *h0 = (TH2F*)f->Get("ToE");
  h0->Draw();
  //TLine *line1 = new TLine(5, 1.1, 100, 1.1);
  //line1->SetLineColor(kRed);
  //line1->SetLineWidth(3);
  //line1->Draw();
  //TLine *line2 = new TLine(5, 2.1, 100, 2.1);
  //line2->SetLineColor(kRed);
  //line2->SetLineWidth(3);
  //line2->Draw();
  h0->GetXaxis()->SetTitle("Energy (keV)");
  TLine *line1 = new TLine(5, 0.74, 9, 0.74);
  line1->SetLineColor(kRed);
  line1->SetLineWidth(3);
  line1->Draw();
  TLine *line2 = new TLine(5, 1.76, 9, 1.76);
  line2->SetLineColor(kRed);
  line2->SetLineWidth(3);
  line2->Draw();
  TLine *line3 = new TLine(9, 0.93, 20, 0.93);
  line3->SetLineColor(kRed);
  line3->SetLineWidth(3);
  line3->Draw();
  TLine *line4 = new TLine(9, 1.53, 20, 1.53);
  line4->SetLineColor(kRed);
  line4->SetLineWidth(3);
  line4->Draw();
  TLine *line5 = new TLine(20, 1.04, 100, 1.04);
  line5->SetLineColor(kRed);
  line5->SetLineWidth(3);
  line5->Draw();
  TLine *line6 = new TLine(20, 1.4, 100, 1.4);
  line6->SetLineColor(kRed);
  line6->SetLineWidth(3);
  line6->Draw();
}
