{
  TChain* ch = new TChain("skimTree", "skimTree");
  ch->Add("/global/u1/j/jrager/low_energy_skim/output/skimDS6*.root");
  //TH1F *nocuts = new TH1F("nocuts", "nocuts", 60, 0, 30);
  //TH1F *cuts = new TH1F("cuts", "cuts", 60, 0, 30);
  //TProfile *tprof = new TProfile("tprof", "tprof", 380, 5, 100, -20, 5);
  //TProfile *tprof = new TProfile("tprof", "tprof", 180, 5, 50, -20, 5);
  //tprof->GetYaxis()->SetTitle("trapETailMin");
  //tprof->GetXaxis()->SetTitle("trapENFCal");
  //TH2F *trapVrun = new TH2F("trapVrun","trapVrun", 5781, 8722, 14503, 160, -30, 10);
  //trapVrun->GetYaxis()->SetTitle("trapETailMin");
  //trapVrun->GetXaxis()->SetTitle("run");
  //TH2F *EVrun = new TH2F("EVrun","EVrun", 5846, 2337, 8183, 120, 0, 30);
  //EVrun->GetYaxis()->SetTitle("trapENFCal (keV)");
  //EVrun->GetXaxis()->SetTitle("run");
  TH2F *twoD = new TH2F("twoD", "twoD", 1000, 0, 100, 400, 0, 10);
  twoD->GetYaxis()->SetTitle("T/E (arb)");
  twoD->GetXaxis()->SetTitle("trapENFCal (keV)");
  //EVrun->GetXaxis()->SetTitle("run");
  //TH1F *htrapETailMin = new TH1F("htrapETailMin","htrapETailMin", 120, -5, 5);
  //htrapETailMin->GetXaxis()->SetTitle("trapETailMin");
  //TLegend *legend = new TLegend(0.1,0.7,0.48,0.9);
  //legend->AddEntry(nocuts,"no cuts","f");
  //legend->AddEntry(cuts,"basic data cleaning","f");
  //legend->AddEntry(twoD,"trapETailMin vs trapENFCal","f");
  //ch->Project("nocuts","trapENFCal");
  //ch->Project("cuts","trapENFCal","trapENFCal>0.8 && gain==0 && mH==1 && isGood && !muVeto && !isLNFill1 && !isLNFill2 && P!=0 && D!=0 && trapETailMin<0.5");
  ch->Project("twoD","kvorrT/trapENFCal:trapENFCal", "gain==0 && mH==1 && isGood && !muVeto && !isLNFill1 && !isLNFill2 && P!=0 && D!=0");
  //ch->Project("tprof","trapETailMin:trapENFCal", "gain==0 && mH==1 && isGood && !muVeto && !isLNFill1 && !isLNFill2 && P!=0 && D!=0");
  //ch->Project("trapVrun","trapETailMin:run", "gain==0 && mH==1 && isGood && !muVeto && !isLNFill1 && !isLNFill2 && P!=0 && D!=0");
  //ch->Project("EVrun","trapENFCal:run", "gain==0 && mH==1 && isGood && !muVeto && !isLNFill1 && !isLNFill2 && P!=0 && D!=0");
  //ch->Project("htrapETailMin","trapETailMin","trapENFCal<3 && gain==0 && mH==1 && isGood && !muVeto && !isLNFill1 && !isLNFill2 && P!=0 && D!=0");
  //nocuts->Draw();
  //nocuts->SetLineColor(kRed);
  //cuts->Draw("same");
  //cuts->SetLineColor(kBlue);
  //legend->Draw();
  twoD->Draw("colz");
  //tprof->Draw();
  //trapVrun->Draw("colz");
  //EVrun->Draw("colz");
  //htrapETailMin->Draw();
  //TLine *line95 = new TLine();
  //line95->SetLineColor(kRed);
  //line95->DrawLine(0.0732813, 0, 0.0732813, 5000000);
}
