#!/bin/bash
#$ -l projectio=1 -j y  -l h_cpu=24:00:00 -l h_vmem=4G -m e  -M ragerj@unc.edu
source ~/.bashrc.ext
#./skim_mjd_data 6 0 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 1 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 2 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 3 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 4 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 5 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 6 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 7 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 8 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 9 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 10 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 11 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 12 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 13 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 14 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 15 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 16 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 17 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 18 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 19 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 20 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 21 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 22 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 23 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 24 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 25 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 26 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 27 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 28 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 29 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 30 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 31 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 32 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 33 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 34 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 35 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 36 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 37 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 38 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 39 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 40 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 41 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 42 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 43 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 44 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 45 -n -l -t 0.7 ~/low_energy_skim/output
#./skim_mjd_data 6 46 -n -l -t 0.7 ~/low_energy_skim/output
./skim_mjd_data 6 47 -n -l -t 0.7 ~/low_energy_skim/output
./skim_mjd_data 6 48 -n -l -t 0.7 ~/low_energy_skim/output
./skim_mjd_data 6 49 -n -l -t 0.7 ~/low_energy_skim/output
./skim_mjd_data 6 50 -n -l -t 0.7 ~/low_energy_skim/output
./skim_mjd_data 6 51 -n -l -t 0.7 ~/low_energy_skim/output
./skim_mjd_data 6 52 -n -l -t 0.7 ~/low_energy_skim/output
./skim_mjd_data 6 53 -n -l -t 0.7 ~/low_energy_skim/output
./skim_mjd_data 6 54 -n -l -t 0.7 ~/low_energy_skim/output
./skim_mjd_data 6 55 -n -l -t 0.7 ~/low_energy_skim/output